[build]
  command = "export NODE_OPTIONS=--openssl-legacy-provider && ./node_modules/.bin/gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "14.21.3"
  NPM_VERSION = "6.14.18"

[build.processing]
  skip_processing = true 