[build]
  command = "node -r ./polyfills.js ./node_modules/.bin/gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "16.19.1"
  NPM_VERSION = "8.19.3"

[build.processing]
  skip_processing = true 